#!/bin/bash
  
 cd
 rm -rf CC
 git clone https://github.com/PONDTY/CC
 cd ../etc/mobile-mining/set-miner
 cp -r online.json offline.json /../root/CC/mobile-mining/set-miner 
 cd
 cd ../etc
 rm -rf mobile-mining
 cd
 cd ../bin
 rm -rf add-ip edit-miner run-miner update backup restore
 cd
 cd CC
 chmod +x setupdate.sh
 sh setupdate.sh
